// fpga/sim/cirradio_bd_tb.sv
// Integration testbench using AXI VIP master agent.
// Run after block design is created in Vivado GUI and HDL wrapper is committed.
`timescale 1ns/1ps
`include "sim_helpers.svh"
module cirradio_bd_tb;
    // NOTE: This testbench requires the Vivado block design (BD) to be
    // generated first using fpga/scripts/create_project.tcl, then exported
    // via Vivado GUI (File > Export > Export Hardware). The BD wrapper
    // (fpga/src/top/cirradio_bd_wrapper.sv) is auto-generated by Vivado
    // and is NOT committed to the repository.
    // To run: open the Vivado project, set sim_1 top to cirradio_bd_tb,
    // and launch simulation. Cannot run standalone without the BD.
    logic clk = 0, rst_n = 0;
    always #5 clk = ~clk;

    // AXI VIP master agent — generated package from axi_vip_mst IP
    import axi_vip_pkg::*;
    import axi_vip_mst_pkg::*;

    axi_mst_agent mst_agent;

    // AXI register addresses (from regs.svh)
    localparam logic [31:0] REG_FHEK_0       = 32'h0000_0000;
    localparam logic [31:0] REG_SLOT_BITMAP  = 32'h0000_0070;
    localparam logic [31:0] REG_HOP_COUNTER  = 32'h0000_0088;
    localparam logic [31:0] AXI_GPIO_DATA    = 32'h4120_0008;

    // Instantiate the full BD wrapper (auto-generated by Vivado)
    // Port list will be filled in after Vivado generates it.
    // Declared here as a placeholder for simulation infrastructure.
    // cirradio_bd_wrapper dut ( ... );

    initial begin
        // mst_agent = new("mst_agent", dut.axi_vip_mst.inst.IF);
        // mst_agent.start_master();
        rst_n = 0; `WAIT_CYCLES(10); rst_n = 1; `WAIT_CYCLES(5);

        // --- Test 1: Write FHEK via AXI, read hop counter ---
        // Write FHEK = 0xAA*32 (8 words)
        // for (int i = 0; i < 8; i++)
        //     mst_agent.AXI4LITE_WRITE_BURST(REG_FHEK_0 + i*4, 0, 32'hAAAA_AAAA, 4'hF, 0);
        // `WAIT_CYCLES(20);
        // logic [31:0] rd;
        // mst_agent.AXI4LITE_READ_BURST(REG_HOP_COUNTER, 0, rd, 0);
        // `CHECK(rd !== 32'hX, "hop counter readable after FHEK load");

        // --- Test 2: Write slot bitmap, verify GPIO ---
        // mst_agent.AXI4LITE_WRITE_BURST(REG_SLOT_BITMAP, 0, 32'h1, 4'hF, 0);
        // `WAIT_CYCLES(10);
        // mst_agent.AXI4LITE_READ_BURST(AXI_GPIO_DATA, 0, rd, 0);
        // `CHECK(rd[0] === 1'b1, "txnrx GPIO = 1 on owned slot 0");

        // Placeholder: BD wrapper not yet generated (requires Vivado GUI)
        $display("cirradio_bd_tb: PLACEHOLDER — run after Vivado BD generation");
        $finish;
    end
    initial begin #1000000; $error("TIMEOUT"); $fatal(1); end
endmodule
